export const mockLighting = [
  {
    id: 1,
    name: "미니멀 버섯 무선 램프",
    categoryId: "lighting",
    price: 38000,
    rating: 0,
    reviewCount: 0,
    liked: false,
    imageUrl: "https://i.ibb.co/Nnxv35Z9/whaudwprj1.webp",
    description: "곡선 쉐이드와 3단 터치 디밍이 돋보이는 모던 무선 무드등",
  },
  {
    id: 2,
    name: "슬림 모니터 라이트바",
    categoryId: "lighting",
    price: 42000,
    rating: 0,
    reviewCount: 0,
    liked: false,
    imageUrl: "https://i.ibb.co/TnszRpc/whaud2wprj.webp",
    description: "눈부심 없이 데스크 작업 영역만 미니멀하게 밝히는 스크린바",
  },
  {
    id: 3,
    name: "매트 메탈 데스크 스탠드",
    categoryId: "lighting",
    price: 54000,
    rating: 0,
    reviewCount: 0,
    liked: false,
    imageUrl: "https://i.ibb.co/8nZPXKDW/whaudwprj4.webp",
    description:
      "직선적인 알루미늄 바디와 정교한 각도 조절이 가능한 작업용 조명",
  },
  {
    id: 4,
    name: "앰비언트 선셋 램프",
    categoryId: "lighting",
    price: 26000,
    rating: 0,
    reviewCount: 0,
    liked: false,
    imageUrl: "https://i.ibb.co/0p6ZRKzV/whaudwprj3.webp",
    description: "벽면에 은은한 빛을 투사해 공간의 무드를 바꾸는 감성 램프",
  },
  {
    id: 5,
    name: "마그네틱 미니 센서등",
    categoryId: "lighting",
    price: 19000,
    rating: 0,
    reviewCount: 0,
    liked: false,
    imageUrl: "https://i.ibb.co/d4d2nxGh/whaudwprj.webp",
    description: "선반이나 프레임에 자석으로 부착해 사용하는 충전식 큐브 조명",
  },
  {
    id: 6,
    name: "글라스 글로브 테이블 램프",
    categoryId: "lighting",
    price: 46000,
    rating: 0,
    reviewCount: 0,
    liked: false,
    imageUrl:
      "https://i.ibb.co/mr4BfqwL/e965dcb2-980a-4ee3-9470-8b9fd4b57198.webp",
    description: "미니멀한 구형 유리 쉐이드로 부드러운 빛을 내는 오브제 조명",
  },
];
